/*
 * This enables the 'smart' control of motor power through the detected distance of the ultrasonic sensor (on dgtl7)
 * Author: JacobLiu001
 * Date: 20 Nov. 2019
 */
#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl7,  ultraSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
const int MAXPOWER = 127;
int getS(int x) {
	if (x == -1) {
		return 0;
	} else if (x <= 20) {
		return 0;
	} else if (x <= 30) {
		return (int)(MAXPOWER * 0.2);
	} else if (x <= 40) {
		return (int)(MAXPOWER * 0.4);
	} else if (x <= 50) {
		return (int)(MAXPOWER * 0.6);
	} else if (x <= 60) {
		return (int)(MAXPOWER * 0.8);
	}
	return MAXPOWER;
}

task main() {
	while (true) {
		int dis = SensorValue[ultraSensor];
		writeDebugStreamLine("%d", dis);
		motor[leftMotor] = motor[rightMotor] = getS(dis);
	}
	stopAllMotors();
}
