/* Selectable Control.c
 * This enables selectable control (Joystick Channel 1&2 / button7UDLR). 
 * The selection can be done by:
 * pressing 5D (for joystick) or 5U (for button), and
 * terminating the current session by pressing 6U
 */

#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void conJoy() {
	while (vexRT[Btn6U] == 0) {
		int x1, x2, y1, y2; // right is positive
		int px = 0, py = 0;
		x1 = vexRT[Ch1];
		x2 = vexRT[Ch4];
		y1 = vexRT[Ch2];
		y2 = vexRT[Ch3];
		if (abs(x1) <= 5) x1 = 0;
		if (abs(x2) <= 5) x2 = 0;
		if (abs(y1) <= 5) y1 = 0;
		if (abs(y2) <= 5) y2 = 0;
		px = (x1 + y1) >> 1;
		py = (-x1 + y1) >> 1;
		motor[leftMotor] = px;
		motor[rightMotor] = py;
	}
}

void conBtn() {
	while (vexRT[Btn6U] == 0) {
		int v7U, v7D, v7L, v7R;
		int px = 0, py = 0;
		v7U = vexRT[Btn7U];
		v7D = vexRT[Btn7D];
		v7L = vexRT[Btn7L];
		v7R = vexRT[Btn7R];
		px = (v7U - v7D - v7L + v7R) * 63;
		py = (v7U - v7D + v7L - v7R) * 63;
		motor[leftMotor] = px;
		motor[rightMotor] = py;
	}
}

task main() {
	while (true) {
		int state = vexRT[Btn5U] - vexRT[Btn5D];
		switch(state) {
			case 1: conBtn(); break;
			case 0: stopAllMotors(); break;
			case -1: conJoy(); break;
			default: stopAllMotors(); break;
		}
	}
}
