/*
 * This is a single-joystick control program for CLAWBOT with Thresholds
 * Author: JacobLiu001
 * Date: 13 Nov. 2019
 */
#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main() {
	while (true) {
		int x1, x2, y1, y2; // right is positive
		int px = 0, py = 0;
		x1 = vexRT[Ch1];
		x2 = vexRT[Ch4];
		y1 = vexRT[Ch2];
		y2 = vexRT[Ch3];
		if (abs(x1) <= 5) x1 = 0;
		if (abs(x2) <= 5) x2 = 0;
		if (abs(y1) <= 5) y1 = 0;
		if (abs(y2) <= 5) y2 = 0;
		px = (x1 + y1) >> 1; // " >> 1 " is the same as " / 2 "
		py = (-x1 + y1) >> 1;
		motor[leftMotor] = px;
		motor[rightMotor] = py;
	}
}
