#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl7,  ultraSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// const int MAXPOWER = 127;
int getX(int iter = 50) {
	long ret = 0;
	for (int i = 0; i < iter; i++) {
		ret += SensorValue[ultraSensor];
	}
	ret /= iter;
	return (int)(ret);
}

task main() {
	bool reverse = false;
	while (true) {
		int dis = getX();
		if (dis > 50) {
			reverse = false;
		} else if (dis < 20) {
			reverse = true;
		}
		if (reverse) {
			motor[leftMotor] = motor[rightMotor] = -25;
		} else {
			motor[leftMotor] = motor[rightMotor] = 127;
		}
		bool v8l = (bool)(vexRT[Btn8L]);
		bool v8u = (bool)(vexRT[Btn8U]);
		if (v8u && !v8l) {
			stopAllMotors();
			wait10Msec(1);
			waitUntil(vexRT[Btn8L] == 1);
		}
	}
	stopAllMotors();
}
